In [34]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
df=pd.read_csv("Iris.csv")
print(df.shape)
print(df.head(5))

(150, 6)
   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa


In [25]:
#assigning column name to data set
#name=['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm','Species']
df.drop('Id',axis=1,inplace=True)
#spe=pd.get_dummies(df['Species'])
#df=pd.concat([df,spe],axis=1)
#df

In [27]:
#splitting the data
x=df.drop('Species',axis=1)
y=df['Species']

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)
print(x_train.shape)
print(x_train)

(120, 4)
     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
130            7.4           2.8            6.1           1.9
19             5.1           3.8            1.5           0.3
27             5.2           3.5            1.5           0.2
96             5.7           2.9            4.2           1.3
42             4.4           3.2            1.3           0.2
..             ...           ...            ...           ...
3              4.6           3.1            1.5           0.2
58             6.6           2.9            4.6           1.3
36             5.5           3.5            1.3           0.2
40             5.0           3.5            1.3           0.3
133            6.3           2.8            5.1           1.5

[120 rows x 4 columns]


In [29]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [30]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [31]:
y_pred=classifier.predict(x_test)
print(y_pred)

['Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor']


In [32]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       0.91      0.91      0.91        11
 Iris-virginica       0.89      0.89      0.89         9

       accuracy                           0.93        30
      macro avg       0.93      0.93      0.93        30
   weighted avg       0.93      0.93      0.93        30

[[10  0  0]
 [ 0 10  1]
 [ 0  1  8]]


In [33]:
classifier.score(x_test,y_test)

0.9333333333333333